import Foundation

public protocol StoryRepository: Sendable {
    func loadStories() async throws -> [Story]
}

public enum StoryRepositoryError: Error, LocalizedError {
    case resourceNotFound
    case decodingFailed

    public var errorDescription: String? {
        switch self {
        case .resourceNotFound: return "Stories resource not found."
        case .decodingFailed: return "Failed to decode stories."
        }
    }
}

public actor LocalStoryRepository: StoryRepository {
    private let bundle: Bundle

    public init(bundle: Bundle? = nil) {
        self.bundle = bundle ?? .module
    }

    public func loadStories() async throws -> [Story] {
        guard let url = bundle.url(forResource: "stories", withExtension: "json") else {
            throw StoryRepositoryError.resourceNotFound
        }
        let data = try Data(contentsOf: url)
        guard let stories = try? JSONDecoder().decode([Story].self, from: data) else {
            throw StoryRepositoryError.decodingFailed
        }
        return stories
    }
}

// Bundle.module is generated by Tuist for resources in this module.
